import { shallowRef } from 'vue'

export const LOCALES = ['zh-Hans', 'en', 'zh-Hant', 'ja'] as const
export type Locale = typeof LOCALES[number]

const LOCALE_KEY = 'mdreader-locale'

const messages = {
  'zh-Hans': {
    appName: '屿阅',
    editorDiscard: '放弃修改', editorConfirmDiscard: '将丢弃当前尚未安全保存的编辑，并重新读取磁盘版本。确认继续吗？', editorDiscardConfirmed: '确认放弃',
    editorReadOnlyNeedsSaveAs: '此文件不能安全原地写回，请先另存为', editorSaveAsRequired: '当前文件系统条件不支持安全原地写回，请另存为后编辑', editorSaveAsFailed: '另存为失败，原文件未改变', editorSaveAsConflict: '另存目标已变化，请重新选择', editorTargetAlreadyOpen: '另存目标已在另一个标签中打开', editorImageSourceInvalid: '所选图片无法安全读取', editorImageFormatInvalid: '仅支持 PNG、JPEG、GIF 或 WebP 图片', editorImageWriteFailed: '图片复制失败，Markdown 未插入',
    editorLeaveBlocked: '当前内容尚未安全保存，请先处理保存失败或外部冲突',
    editorInsertImage: '插入本地图片', editorImageInsertRejected: '当前编辑容量不足，图片文件已回滚',
    editorRetry: '重试', editorSaveAs: '另存为', editorUseDisk: '使用磁盘版本', editorOverwrite: '用当前内容覆盖', editorConfirmOverwrite: '磁盘版本会被当前编辑内容替换。确认继续吗？', editorCancel: '取消', editorOverwriteConfirmed: '确认覆盖',
    editorWorkspace: '编辑工作区', editorSource: '源码', editorPreview: '预览', editorFind: '查找与替换', editorMore: '更多格式',
    editorSearchFind: '查找', editorSearchReplace: '替换', editorSearchNext: '下一个', editorSearchPrevious: '上一个', editorSearchAll: '全部', editorSearchMatchCase: '区分大小写', editorSearchRegexp: '正则表达式', editorSearchByWord: '全字匹配', editorSearchReplaceOne: '替换', editorSearchReplaceAll: '全部替换', editorSearchClose: '关闭', editorSearchCurrentMatch: '当前匹配', editorSearchOnLine: '位于行', editorSearchReplacedMatchOnLine: '已替换第 $ 行的匹配', editorSearchReplacedMatches: '已替换 $ 处匹配', editorGoToLine: '跳转到行', editorGo: '跳转', editorControlCharacter: '控制字符', editorSelectionDeleted: '已删除所选内容',
    open: '打开', openMarkdownFile: '打开 Markdown 文件', readingSettings: '阅读设置', closeNotification: '关闭提示', editDocument: '编辑', doneEditing: '完成', editorToolbar: '编辑工具', editorPlaceholder: '文本', editorUndo: '撤销', editorRedo: '重做', editorHeading: '标题', editorBold: '加粗', editorItalic: '斜体', editorStrikethrough: '删除线', editorBulletList: '无序列表', editorOrderedList: '有序列表', editorTaskList: '任务列表', editorQuote: '引用', editorLink: '链接', editorInlineCode: '行内代码', editorCodeBlock: '代码块', editorWritePending: '待写入', editorWriting: '正在保存…', editorSaved: '已保存', editorWriteFailed: '保存失败', editorConflict: '文件已在外部修改', editorRecoveryRequired: '多份内容已保留', editorRecoverySaveCopy: '另存当前内容', editorRecoveryReveal: '在 Finder 中显示', editorRecoveryAcknowledge: '我已处理', editorRecoveryActionFailed: '无法完成保全内容处理', editorRecoveryActionRefreshed: '处理凭证已刷新，请重试刚才的操作', editorCapacityExceeded: '编辑会话容量已满，请先关闭其他文档', editorFinishPending: '请等待当前内容安全保存后再完成编辑',
    importingDocument: '正在导入文档…', renderingDocument: '正在渲染文档…', welcomeTitle: '把 Markdown 读成文档', welcomeDescription: '打开本地文件，专注于内容。远程资源默认保持阻断。', welcomeHint: '支持 .md / .markdown / .txt · 也可以将文件拖入窗口', dropToOpen: '释放以打开 Markdown 文件',
    documentOpenFailed: '无法打开文档', unsupportedFormat: '不支持的文档格式', documentTooLarge: '文档超过 10 MiB 限制', documentReadFailed: '文档读取失败，已保留上一次内容', documentIdentityChanged: '文件身份已变化，请重新打开文档', documentNotUtf8: '文档不是有效的 UTF-8 文本', documentTabLimit: '打开的文档已达到 32 个上限', documentWatchFailed: '文件变化监听未启动', markdownAstLimit: '文档结构超过安全限制', markdownRenderLimit: '文档渲染结果超过安全限制', markdownRenderFailed: '文档渲染失败', renderTimeout: '文档渲染超时，其他标签仍可继续使用', renderCrash: '文档渲染进程已恢复，请重试', renderQueueLimit: '同时处理的文档超过安全容量，请稍后重试', renderProtocolError: '文档渲染通信异常，请重试', renderCancelled: '文档渲染已取消', documentProcessingFailed: '文档处理失败', openDialogFailed: '打开文件对话框失败', printDocumentMissing: '请先打开 Markdown 文档，再导出 PDF', printDialogFailed: '无法打开系统打印面板', appInitializeFailed: '应用初始化失败',
    themeLight: '浅色', themeDark: '深色', themeSystem: '跟随系统', themeFollowingSystem: '跟随系统（当前为{theme}）', currentThemeAction: '当前：{current}；点击切换到{next}', themeChanged: '已切换到{theme}模式',
    language: '语言', readingAppearance: '阅读外观', fontSize: '文字大小', decreaseFont: '缩小文字', increaseFont: '放大文字', resetFont: '恢复默认文字大小', switchComfortableWidth: '切换为舒适宽度', switchFullWidth: '切换为完整宽度', remoteImages: '远程图片', remoteImagesAllowed: '当前标签已允许远程图片', loadRemoteImages: '加载此文档远程图片', loadRemoteImagesHint: '仅为当前标签临时加载 HTTPS 图片', closeReadingSettings: '关闭阅读设置',
    searchDocument: '搜索文档', searchResults: '搜索结果', noResults: '无结果', previousMatch: '上一个匹配', nextMatch: '下一个匹配', closeSearch: '关闭搜索',
    openDocuments: '打开的文档', switchTo: '切换到 {name}', documentHasError: '此文档有错误', needsAttention: '需检查', closeDocument: '关闭文档', documentTabActions: '文档标签操作', moreDocuments: '更多文档（{count} 个）', hiddenDocuments: '其他打开的文档', close: '关闭', closeOthers: '关闭其他', closeLeft: '关闭左侧', closeRight: '关闭右侧', closeAll: '关闭全部',
    outline: '目录', headingNavigation: '标题导航', retryDocument: '重试此文档', retry: '重试', outlineLocationMissing: '未找到该目录位置', code: '代码', codeLanguage: '语言：{language}', copyCode: '复制代码', copied: '已复制', codeCopied: '代码已复制', copyCodeFailed: '复制代码失败', imageUnableToLoad: '图片无法加载', imageSourceBlocked: '图片来源已阻断', remoteImageBlocked: '远程图片已阻断', remoteImageBlockedWithAlt: '远程图片已阻断：{alt}', loadForCurrentTab: '仅为当前标签加载', openImagePreview: '打开图片预览', openImagePreviewWithAlt: '打开图片预览：{alt}',
    mermaidDiagram: 'Mermaid 图表', mermaidLimit: 'Mermaid 图表超过安全限制', mermaidBlocked: 'Mermaid 图表内容已阻断', mermaidRenderFailed: 'Mermaid 图表渲染失败', mermaidUnsafeOutput: 'Mermaid 输出未通过安全检查', openMermaidDiagram: '打开 Mermaid 图表：{title}', mermaidTimeout: 'Mermaid 图表渲染超时', mermaidDeferred: '图表较多，已暂停后续 Mermaid 渲染。', continueRendering: '继续渲染', continueMermaidRendering: '继续渲染剩余 Mermaid 图表', externalLinkFailed: '外部链接无法打开', linkTypeBlocked: '该链接类型已阻断',
    imagePreview: '大图预览', imagePreviewTools: '大图预览工具栏', zoomOut: '缩小预览', zoomIn: '放大预览', zoomStatus: '当前缩放 {percent}%，点击恢复适应窗口', resetZoom: '恢复适应窗口', exportPng: '导出 PNG', pngExported: 'PNG 已导出', pngExportLimit: 'PNG 导出超过安全限制', pngExportFailed: 'PNG 导出失败', closeImagePreview: '关闭大图',
  },
  en: {
    appName: '屿阅',
    editorDiscard: 'Discard edits', editorConfirmDiscard: 'Unsafely saved edits will be discarded and the disk version reloaded. Continue?', editorDiscardConfirmed: 'Discard edits',
    editorReadOnlyNeedsSaveAs: 'This file cannot be safely written in place. Save As before editing.', editorSaveAsRequired: 'Safe in-place writing is unavailable here. Save As before editing.', editorSaveAsFailed: 'Save As failed; the original file was unchanged.', editorSaveAsConflict: 'The Save As target changed. Choose it again.', editorTargetAlreadyOpen: 'The Save As target is already open in another tab.', editorImageSourceInvalid: 'The selected image could not be read safely.', editorImageFormatInvalid: 'Only PNG, JPEG, GIF, or WebP images are supported.', editorImageWriteFailed: 'The image could not be copied, so no Markdown was inserted.',
    editorLeaveBlocked: 'Your current edits are not safely saved. Resolve the save failure or external conflict first.',
    editorInsertImage: 'Insert local image', editorImageInsertRejected: 'The edit limit was reached; the copied image was rolled back.',
    editorRetry: 'Retry', editorSaveAs: 'Save As', editorUseDisk: 'Use disk version', editorOverwrite: 'Overwrite with current content', editorConfirmOverwrite: 'The disk version will be replaced by your current edits. Continue?', editorCancel: 'Cancel', editorOverwriteConfirmed: 'Confirm overwrite',
    editorWorkspace: 'Editing workspace', editorSource: 'Source', editorPreview: 'Preview', editorFind: 'Find and replace', editorMore: 'More formatting',
    editorSearchFind: 'Find', editorSearchReplace: 'Replace', editorSearchNext: 'Next', editorSearchPrevious: 'Previous', editorSearchAll: 'All', editorSearchMatchCase: 'Match case', editorSearchRegexp: 'Regular expression', editorSearchByWord: 'Whole words', editorSearchReplaceOne: 'Replace', editorSearchReplaceAll: 'Replace all', editorSearchClose: 'Close', editorSearchCurrentMatch: 'Current match', editorSearchOnLine: 'on line', editorSearchReplacedMatchOnLine: 'Replaced match on line $', editorSearchReplacedMatches: 'Replaced $ matches', editorGoToLine: 'Go to line', editorGo: 'Go', editorControlCharacter: 'Control character', editorSelectionDeleted: 'Selection deleted',
    open: 'Open', openMarkdownFile: 'Open Markdown file', readingSettings: 'Reading settings', closeNotification: 'Dismiss notification', editDocument: 'Edit', doneEditing: 'Done', editorToolbar: 'Editing tools', editorPlaceholder: 'text', editorUndo: 'Undo', editorRedo: 'Redo', editorHeading: 'Heading', editorBold: 'Bold', editorItalic: 'Italic', editorStrikethrough: 'Strikethrough', editorBulletList: 'Bullet list', editorOrderedList: 'Ordered list', editorTaskList: 'Task list', editorQuote: 'Quote', editorLink: 'Link', editorInlineCode: 'Inline code', editorCodeBlock: 'Code block', editorWritePending: 'Pending write', editorWriting: 'Saving…', editorSaved: 'Saved', editorWriteFailed: 'Save failed', editorConflict: 'File changed externally', editorRecoveryRequired: 'Multiple contents preserved', editorRecoverySaveCopy: 'Save current content', editorRecoveryReveal: 'Show in Finder', editorRecoveryAcknowledge: 'I handled this', editorRecoveryActionFailed: 'Could not handle the preserved content.', editorRecoveryActionRefreshed: 'The recovery authorization was refreshed. Retry the action.', editorCapacityExceeded: 'The editor session capacity is full. Close another document first.', editorFinishPending: 'Wait until the current content has been saved safely before finishing.',
    importingDocument: 'Importing document…', renderingDocument: 'Rendering document…', welcomeTitle: 'Read Markdown as a document', welcomeDescription: 'Open a local file and focus on its content. Remote resources stay blocked by default.', welcomeHint: 'Supports .md / .markdown / .txt · You can also drop a file into this window', dropToOpen: 'Drop to open a Markdown file',
    documentOpenFailed: 'Unable to open document', unsupportedFormat: 'Unsupported document format', documentTooLarge: 'Document exceeds the 10 MiB limit', documentReadFailed: 'Unable to read document; previous content is retained', documentIdentityChanged: 'File identity changed. Please open the document again.', documentNotUtf8: 'Document is not valid UTF-8 text', documentTabLimit: 'The 32-document limit has been reached', documentWatchFailed: 'File-change monitoring did not start', markdownAstLimit: 'Document structure exceeds the safety limit', markdownRenderLimit: 'Rendered document exceeds the safety limit', markdownRenderFailed: 'Unable to render document', renderTimeout: 'Document rendering timed out; other tabs remain available', renderCrash: 'Document renderer recovered. Please try again.', renderQueueLimit: 'Too many documents are being processed. Please try again later.', renderProtocolError: 'Document rendering communication failed. Please try again.', renderCancelled: 'Document rendering was cancelled', documentProcessingFailed: 'Document processing failed', openDialogFailed: 'Unable to open the file picker', printDocumentMissing: 'Open a Markdown document before exporting a PDF', printDialogFailed: 'Unable to open the system print panel', appInitializeFailed: 'App initialization failed',
    themeLight: 'Light', themeDark: 'Dark', themeSystem: 'System', themeFollowingSystem: 'System ({theme} now)', currentThemeAction: 'Current: {current}; click to switch to {next}', themeChanged: 'Switched to {theme} mode',
    language: 'Language', readingAppearance: 'Reading appearance', fontSize: 'Text size', decreaseFont: 'Decrease text size', increaseFont: 'Increase text size', resetFont: 'Reset text size', switchComfortableWidth: 'Use comfortable width', switchFullWidth: 'Use full width', remoteImages: 'Remote images', remoteImagesAllowed: 'Remote images are allowed for this tab', loadRemoteImages: 'Load remote images for this document', loadRemoteImagesHint: 'Temporarily load HTTPS images for this tab only', closeReadingSettings: 'Close reading settings',
    searchDocument: 'Search document', searchResults: 'Search results', noResults: 'No results', previousMatch: 'Previous match', nextMatch: 'Next match', closeSearch: 'Close search',
    openDocuments: 'Open documents', switchTo: 'Switch to {name}', documentHasError: 'This document has an error', needsAttention: 'Needs attention', closeDocument: 'Close document', documentTabActions: 'Document tab actions', moreDocuments: 'More documents ({count})', hiddenDocuments: 'Other open documents', close: 'Close', closeOthers: 'Close others', closeLeft: 'Close tabs to the left', closeRight: 'Close tabs to the right', closeAll: 'Close all',
    outline: 'Outline', headingNavigation: 'Heading navigation', retryDocument: 'Retry this document', retry: 'Retry', outlineLocationMissing: 'Outline location was not found', code: 'Code', codeLanguage: 'Language: {language}', copyCode: 'Copy code', copied: 'Copied', codeCopied: 'Code copied', copyCodeFailed: 'Unable to copy code', imageUnableToLoad: 'Unable to load image', imageSourceBlocked: 'Image source is blocked', remoteImageBlocked: 'Remote image is blocked', remoteImageBlockedWithAlt: 'Remote image is blocked: {alt}', loadForCurrentTab: 'Load for this tab only', openImagePreview: 'Open image preview', openImagePreviewWithAlt: 'Open image preview: {alt}',
    mermaidDiagram: 'Mermaid diagram', mermaidLimit: 'Mermaid diagram exceeds the safety limit', mermaidBlocked: 'Mermaid diagram content is blocked', mermaidRenderFailed: 'Unable to render Mermaid diagram', mermaidUnsafeOutput: 'Mermaid output did not pass the safety check', openMermaidDiagram: 'Open Mermaid diagram: {title}', mermaidTimeout: 'Mermaid diagram rendering timed out', mermaidDeferred: 'There are many diagrams. Further Mermaid rendering is paused.', continueRendering: 'Continue rendering', continueMermaidRendering: 'Continue rendering remaining Mermaid diagrams', externalLinkFailed: 'Unable to open external link', linkTypeBlocked: 'This link type is blocked',
    imagePreview: 'Large image preview', imagePreviewTools: 'Large image preview tools', zoomOut: 'Zoom out', zoomIn: 'Zoom in', zoomStatus: 'Current zoom {percent}%; click to fit window', resetZoom: 'Fit window', exportPng: 'Export PNG', pngExported: 'PNG exported', pngExportLimit: 'PNG export exceeds the safety limit', pngExportFailed: 'PNG export failed', closeImagePreview: 'Close image preview',
  },
  'zh-Hant': {
    appName: '屿阅',
    editorDiscard: '放棄修改', editorConfirmDiscard: '將捨棄目前尚未安全儲存的編輯，並重新讀取磁碟版本。確定繼續嗎？', editorDiscardConfirmed: '確認放棄',
    editorReadOnlyNeedsSaveAs: '此檔案無法安全原地寫回，請先另存新檔', editorSaveAsRequired: '目前檔案系統條件不支援安全原地寫回，請另存新檔後編輯', editorSaveAsFailed: '另存新檔失敗，原檔案未變更', editorSaveAsConflict: '另存目標已變更，請重新選擇', editorTargetAlreadyOpen: '另存目標已在另一個分頁中開啟', editorImageSourceInvalid: '所選圖片無法安全讀取', editorImageFormatInvalid: '僅支援 PNG、JPEG、GIF 或 WebP 圖片', editorImageWriteFailed: '圖片複製失敗，未插入 Markdown',
    editorLeaveBlocked: '目前內容尚未安全儲存，請先處理儲存失敗或外部衝突',
    editorInsertImage: '插入本機圖片', editorImageInsertRejected: '目前編輯容量不足，圖片檔案已回復',
    editorRetry: '重試', editorSaveAs: '另存新檔', editorUseDisk: '使用磁碟版本', editorOverwrite: '以目前內容覆蓋', editorConfirmOverwrite: '磁碟版本將由目前編輯內容取代。確定繼續嗎？', editorCancel: '取消', editorOverwriteConfirmed: '確認覆蓋',
    editorWorkspace: '編輯工作區', editorSource: '原始碼', editorPreview: '預覽', editorFind: '尋找與取代', editorMore: '更多格式',
    editorSearchFind: '尋找', editorSearchReplace: '取代', editorSearchNext: '下一個', editorSearchPrevious: '上一個', editorSearchAll: '全部', editorSearchMatchCase: '區分大小寫', editorSearchRegexp: '規則運算式', editorSearchByWord: '全字相符', editorSearchReplaceOne: '取代', editorSearchReplaceAll: '全部取代', editorSearchClose: '關閉', editorSearchCurrentMatch: '目前相符項目', editorSearchOnLine: '位於第', editorSearchReplacedMatchOnLine: '已取代第 $ 行的相符項目', editorSearchReplacedMatches: '已取代 $ 個相符項目', editorGoToLine: '跳至行', editorGo: '跳至', editorControlCharacter: '控制字元', editorSelectionDeleted: '已刪除所選內容',
    open: '開啟', openMarkdownFile: '開啟 Markdown 檔案', readingSettings: '閱讀設定', closeNotification: '關閉提示', editDocument: '編輯', doneEditing: '完成', editorToolbar: '編輯工具', editorPlaceholder: '文字', editorUndo: '復原', editorRedo: '重做', editorHeading: '標題', editorBold: '粗體', editorItalic: '斜體', editorStrikethrough: '刪除線', editorBulletList: '項目清單', editorOrderedList: '編號清單', editorTaskList: '工作清單', editorQuote: '引用', editorLink: '連結', editorInlineCode: '行內程式碼', editorCodeBlock: '程式碼區塊', editorWritePending: '等待寫入', editorWriting: '正在儲存…', editorSaved: '已儲存', editorWriteFailed: '儲存失敗', editorConflict: '檔案已在外部修改', editorRecoveryRequired: '已保留多份內容', editorRecoverySaveCopy: '另存目前內容', editorRecoveryReveal: '在 Finder 中顯示', editorRecoveryAcknowledge: '我已處理', editorRecoveryActionFailed: '無法完成保全內容處理', editorRecoveryActionRefreshed: '處理憑證已更新，請重試剛才的操作', editorCapacityExceeded: '編輯工作階段容量已滿，請先關閉其他文件', editorFinishPending: '請等待目前內容安全儲存後再完成編輯',
    importingDocument: '正在匯入文件…', renderingDocument: '正在轉譯文件…', welcomeTitle: '把 Markdown 讀成文件', welcomeDescription: '開啟本機檔案，專注於內容。遠端資源預設保持封鎖。', welcomeHint: '支援 .md / .markdown / .txt · 也可以將檔案拖入視窗', dropToOpen: '放開以開啟 Markdown 檔案',
    documentOpenFailed: '無法開啟文件', unsupportedFormat: '不支援的文件格式', documentTooLarge: '文件超過 10 MiB 限制', documentReadFailed: '文件讀取失敗，已保留上一次內容', documentIdentityChanged: '檔案身分已變更，請重新開啟文件', documentNotUtf8: '文件不是有效的 UTF-8 文字', documentTabLimit: '開啟的文件已達 32 個上限', documentWatchFailed: '檔案變更監聽未啟動', markdownAstLimit: '文件結構超過安全限制', markdownRenderLimit: '文件轉譯結果超過安全限制', markdownRenderFailed: '文件轉譯失敗', renderTimeout: '文件轉譯逾時，其他分頁仍可繼續使用', renderCrash: '文件轉譯程序已恢復，請重試', renderQueueLimit: '同時處理的文件超過安全容量，請稍後重試', renderProtocolError: '文件轉譯通訊異常，請重試', renderCancelled: '文件轉譯已取消', documentProcessingFailed: '文件處理失敗', openDialogFailed: '開啟檔案對話框失敗', printDocumentMissing: '請先開啟 Markdown 文件，再匯出 PDF', printDialogFailed: '無法開啟系統列印面板', appInitializeFailed: '應用程式初始化失敗',
    themeLight: '淺色', themeDark: '深色', themeSystem: '跟隨系統', themeFollowingSystem: '跟隨系統（目前為{theme}）', currentThemeAction: '目前：{current}；點擊切換至{next}', themeChanged: '已切換至{theme}模式',
    language: '語言', readingAppearance: '閱讀外觀', fontSize: '文字大小', decreaseFont: '縮小文字', increaseFont: '放大文字', resetFont: '回復預設文字大小', switchComfortableWidth: '切換為舒適寬度', switchFullWidth: '切換為完整寬度', remoteImages: '遠端圖片', remoteImagesAllowed: '目前分頁已允許遠端圖片', loadRemoteImages: '載入此文件遠端圖片', loadRemoteImagesHint: '僅為目前分頁暫時載入 HTTPS 圖片', closeReadingSettings: '關閉閱讀設定',
    searchDocument: '搜尋文件', searchResults: '搜尋結果', noResults: '沒有結果', previousMatch: '上一個符合項目', nextMatch: '下一個符合項目', closeSearch: '關閉搜尋',
    openDocuments: '已開啟的文件', switchTo: '切換至 {name}', documentHasError: '此文件有錯誤', needsAttention: '需檢查', closeDocument: '關閉文件', documentTabActions: '文件分頁動作', moreDocuments: '更多文件（{count} 個）', hiddenDocuments: '其他已開啟的文件', close: '關閉', closeOthers: '關閉其他', closeLeft: '關閉左側', closeRight: '關閉右側', closeAll: '關閉全部',
    outline: '目錄', headingNavigation: '標題導覽', retryDocument: '重試此文件', retry: '重試', outlineLocationMissing: '找不到該目錄位置', code: '程式碼', codeLanguage: '語言：{language}', copyCode: '複製程式碼', copied: '已複製', codeCopied: '程式碼已複製', copyCodeFailed: '複製程式碼失敗', imageUnableToLoad: '圖片無法載入', imageSourceBlocked: '圖片來源已封鎖', remoteImageBlocked: '遠端圖片已封鎖', remoteImageBlockedWithAlt: '遠端圖片已封鎖：{alt}', loadForCurrentTab: '僅為目前分頁載入', openImagePreview: '開啟圖片預覽', openImagePreviewWithAlt: '開啟圖片預覽：{alt}',
    mermaidDiagram: 'Mermaid 圖表', mermaidLimit: 'Mermaid 圖表超過安全限制', mermaidBlocked: 'Mermaid 圖表內容已封鎖', mermaidRenderFailed: 'Mermaid 圖表轉譯失敗', mermaidUnsafeOutput: 'Mermaid 輸出未通過安全檢查', openMermaidDiagram: '開啟 Mermaid 圖表：{title}', mermaidTimeout: 'Mermaid 圖表轉譯逾時', mermaidDeferred: '圖表較多，已暫停後續 Mermaid 轉譯。', continueRendering: '繼續轉譯', continueMermaidRendering: '繼續轉譯剩餘 Mermaid 圖表', externalLinkFailed: '無法開啟外部連結', linkTypeBlocked: '此連結類型已封鎖',
    imagePreview: '大圖預覽', imagePreviewTools: '大圖預覽工具列', zoomOut: '縮小預覽', zoomIn: '放大預覽', zoomStatus: '目前縮放 {percent}%，點擊回復適應視窗', resetZoom: '適應視窗', exportPng: '匯出 PNG', pngExported: 'PNG 已匯出', pngExportLimit: 'PNG 匯出超過安全限制', pngExportFailed: 'PNG 匯出失敗', closeImagePreview: '關閉大圖',
  },
  ja: {
    appName: '屿阅',
    editorDiscard: '編集を破棄', editorConfirmDiscard: '安全に保存されていない編集を破棄し、ディスク版を再読み込みします。続けますか？', editorDiscardConfirmed: '編集を破棄',
    editorReadOnlyNeedsSaveAs: 'このファイルには安全に上書きできません。編集前に別名で保存してください。', editorSaveAsRequired: 'この場所では安全な上書きができません。別名で保存してから編集してください。', editorSaveAsFailed: '別名での保存に失敗しました。元のファイルは変更されていません。', editorSaveAsConflict: '保存先が変更されました。もう一度選択してください。', editorTargetAlreadyOpen: '保存先は別のタブですでに開かれています。', editorImageSourceInvalid: '選択した画像を安全に読み取れません。', editorImageFormatInvalid: 'PNG、JPEG、GIF、WebP 画像のみ対応しています。', editorImageWriteFailed: '画像をコピーできなかったため、Markdown は挿入されませんでした。',
    editorLeaveBlocked: '現在の編集内容は安全に保存されていません。保存エラーまたは外部競合を先に解決してください。',
    editorInsertImage: 'ローカル画像を挿入', editorImageInsertRejected: '編集容量の上限に達したため、コピーした画像を元に戻しました。',
    editorRetry: '再試行', editorSaveAs: '別名で保存', editorUseDisk: 'ディスク版を使用', editorOverwrite: '現在の内容で上書き', editorConfirmOverwrite: 'ディスク上の版を現在の編集内容で置き換えます。続けますか？', editorCancel: 'キャンセル', editorOverwriteConfirmed: '上書きを確認',
    editorWorkspace: '編集ワークスペース', editorSource: 'ソース', editorPreview: 'プレビュー', editorFind: '検索と置換', editorMore: 'その他の書式',
    editorSearchFind: '検索', editorSearchReplace: '置換', editorSearchNext: '次へ', editorSearchPrevious: '前へ', editorSearchAll: 'すべて', editorSearchMatchCase: '大文字と小文字を区別', editorSearchRegexp: '正規表現', editorSearchByWord: '単語単位', editorSearchReplaceOne: '置換', editorSearchReplaceAll: 'すべて置換', editorSearchClose: '閉じる', editorSearchCurrentMatch: '現在の一致', editorSearchOnLine: '行', editorSearchReplacedMatchOnLine: '$ 行目の一致を置換しました', editorSearchReplacedMatches: '$ 件の一致を置換しました', editorGoToLine: '指定行へ移動', editorGo: '移動', editorControlCharacter: '制御文字', editorSelectionDeleted: '選択範囲を削除しました',
    open: '開く', openMarkdownFile: 'Markdown ファイルを開く', readingSettings: '閲覧設定', closeNotification: '通知を閉じる', editDocument: '編集', doneEditing: '完了', editorToolbar: '編集ツール', editorPlaceholder: 'テキスト', editorUndo: '元に戻す', editorRedo: 'やり直す', editorHeading: '見出し', editorBold: '太字', editorItalic: '斜体', editorStrikethrough: '取り消し線', editorBulletList: '箇条書き', editorOrderedList: '番号付きリスト', editorTaskList: 'タスクリスト', editorQuote: '引用', editorLink: 'リンク', editorInlineCode: 'インラインコード', editorCodeBlock: 'コードブロック', editorWritePending: '書き込み待ち', editorWriting: '保存中…', editorSaved: '保存済み', editorWriteFailed: '保存に失敗', editorConflict: 'ファイルが外部で変更されました', editorRecoveryRequired: '複数の内容を保持しました', editorRecoverySaveCopy: '現在の内容を別名保存', editorRecoveryReveal: 'Finder に表示', editorRecoveryAcknowledge: '処理済みにする', editorRecoveryActionFailed: '保持した内容を処理できませんでした', editorRecoveryActionRefreshed: '復旧用の認証を更新しました。もう一度操作してください。', editorCapacityExceeded: '編集セッションの容量がいっぱいです。先に別の文書を閉じてください', editorFinishPending: '現在の内容が安全に保存されるまで編集を完了できません',
    importingDocument: '文書を読み込み中…', renderingDocument: '文書を描画中…', welcomeTitle: 'Markdown を文書として読む', welcomeDescription: 'ローカルファイルを開いて内容に集中できます。リモートリソースは既定でブロックされます。', welcomeHint: '.md / .markdown / .txt に対応 · ファイルをウィンドウにドロップすることもできます', dropToOpen: 'ドロップして Markdown ファイルを開く',
    documentOpenFailed: '文書を開けません', unsupportedFormat: 'サポートされていない文書形式です', documentTooLarge: '文書が 10 MiB の上限を超えています', documentReadFailed: '文書を読み取れません。前回の内容は保持されています', documentIdentityChanged: 'ファイルの識別情報が変わりました。もう一度開いてください', documentNotUtf8: '文書は有効な UTF-8 テキストではありません', documentTabLimit: '開ける文書は 32 件までです', documentWatchFailed: 'ファイル変更の監視を開始できませんでした', markdownAstLimit: '文書構造が安全上限を超えています', markdownRenderLimit: '文書の描画結果が安全上限を超えています', markdownRenderFailed: '文書を描画できません', renderTimeout: '文書の描画がタイムアウトしました。他のタブは引き続き使用できます', renderCrash: '文書レンダラーが復旧しました。もう一度お試しください', renderQueueLimit: '同時に処理する文書が安全容量を超えています。しばらくしてからお試しください', renderProtocolError: '文書描画の通信エラーです。もう一度お試しください', renderCancelled: '文書の描画は取り消されました', documentProcessingFailed: '文書の処理に失敗しました', openDialogFailed: 'ファイル選択画面を開けません', printDocumentMissing: 'PDF を書き出す前に Markdown 文書を開いてください', printDialogFailed: 'システムの印刷パネルを開けません', appInitializeFailed: 'アプリの初期化に失敗しました',
    themeLight: 'ライト', themeDark: 'ダーク', themeSystem: 'システムに従う', themeFollowingSystem: 'システムに従う（現在：{theme}）', currentThemeAction: '現在：{current}。クリックして{next}に切り替え', themeChanged: '{theme}モードに切り替えました',
    language: '言語', readingAppearance: '閲覧表示', fontSize: '文字サイズ', decreaseFont: '文字を小さくする', increaseFont: '文字を大きくする', resetFont: '文字サイズをリセット', switchComfortableWidth: '読みやすい幅に切り替え', switchFullWidth: '全幅に切り替え', remoteImages: 'リモート画像', remoteImagesAllowed: 'このタブではリモート画像が許可されています', loadRemoteImages: 'この文書のリモート画像を読み込む', loadRemoteImagesHint: 'このタブでのみ HTTPS 画像を一時的に読み込む', closeReadingSettings: '閲覧設定を閉じる',
    searchDocument: '文書を検索', searchResults: '検索結果', noResults: '結果なし', previousMatch: '前の一致', nextMatch: '次の一致', closeSearch: '検索を閉じる',
    openDocuments: '開いている文書', switchTo: '{name} に切り替える', documentHasError: 'この文書にはエラーがあります', needsAttention: '要確認', closeDocument: '文書を閉じる', documentTabActions: '文書タブの操作', moreDocuments: '他の文書（{count} 件）', hiddenDocuments: '他の開いている文書', close: '閉じる', closeOthers: '他を閉じる', closeLeft: '左側を閉じる', closeRight: '右側を閉じる', closeAll: 'すべて閉じる',
    outline: '目次', headingNavigation: '見出しナビゲーション', retryDocument: 'この文書を再試行', retry: '再試行', outlineLocationMissing: '目次の位置が見つかりません', code: 'コード', codeLanguage: '言語：{language}', copyCode: 'コードをコピー', copied: 'コピー済み', codeCopied: 'コードをコピーしました', copyCodeFailed: 'コードをコピーできません', imageUnableToLoad: '画像を読み込めません', imageSourceBlocked: '画像ソースはブロックされています', remoteImageBlocked: 'リモート画像はブロックされています', remoteImageBlockedWithAlt: 'リモート画像はブロックされています：{alt}', loadForCurrentTab: 'このタブだけで読み込む', openImagePreview: '画像プレビューを開く', openImagePreviewWithAlt: '画像プレビューを開く：{alt}',
    mermaidDiagram: 'Mermaid 図', mermaidLimit: 'Mermaid 図が安全上限を超えています', mermaidBlocked: 'Mermaid 図の内容はブロックされています', mermaidRenderFailed: 'Mermaid 図を描画できません', mermaidUnsafeOutput: 'Mermaid の出力は安全検査に通りませんでした', openMermaidDiagram: 'Mermaid 図を開く：{title}', mermaidTimeout: 'Mermaid 図の描画がタイムアウトしました', mermaidDeferred: '図が多いため、以降の Mermaid 描画を一時停止しました。', continueRendering: '描画を続ける', continueMermaidRendering: '残りの Mermaid 図を描画する', externalLinkFailed: '外部リンクを開けません', linkTypeBlocked: 'このリンク形式はブロックされています',
    imagePreview: '大きな画像プレビュー', imagePreviewTools: '大きな画像プレビューのツール', zoomOut: '縮小', zoomIn: '拡大', zoomStatus: '現在の倍率 {percent}%。クリックしてウィンドウに合わせる', resetZoom: 'ウィンドウに合わせる', exportPng: 'PNG を書き出す', pngExported: 'PNG を書き出しました', pngExportLimit: 'PNG の書き出しが安全上限を超えています', pngExportFailed: 'PNG の書き出しに失敗しました', closeImagePreview: '大きな画像プレビューを閉じる',
  },
} as const

export type MessageKey = keyof typeof messages['zh-Hans']

function isLocale(value: string | null | undefined): value is Locale {
  return typeof value === 'string' && (LOCALES as readonly string[]).includes(value)
}

export function resolveInitialLocale(storedLocale: string | null | undefined, systemLocale: string | null | undefined): Locale {
  if (isLocale(storedLocale)) return storedLocale
  const normalized = systemLocale?.toLowerCase() ?? ''
  if (normalized.startsWith('zh-tw') || normalized.startsWith('zh-hk') || normalized.startsWith('zh-mo')) return 'zh-Hant'
  if (normalized.startsWith('en')) return 'en'
  if (normalized.startsWith('ja')) return 'ja'
  return 'zh-Hans'
}

function storedLocale() {
  if (typeof localStorage === 'undefined') return null
  return localStorage.getItem(LOCALE_KEY)
}

const currentLocale = shallowRef<Locale>(resolveInitialLocale(storedLocale(), typeof navigator === 'undefined' ? null : navigator.language))

export function useLocale() {
  function setLocale(locale: Locale) {
    currentLocale.value = locale
    if (typeof localStorage !== 'undefined') localStorage.setItem(LOCALE_KEY, locale)
  }

  function t(key: MessageKey, values: Record<string, string | number> = {}) {
    return messages[currentLocale.value][key].replace(/\{(\w+)\}/g, (placeholder, name) => String(values[name] ?? placeholder))
  }

  return {
    currentLocale,
    localeOptions: [
      { value: 'zh-Hans' as const, label: '简体中文' },
      { value: 'en' as const, label: 'English' },
      { value: 'zh-Hant' as const, label: '繁體中文' },
      { value: 'ja' as const, label: '日本語' },
    ],
    setLocale,
    t,
  }
}
